table _Misuresupporto
	lineageTag: c4e10dc1-f64c-420c-85c6-f1c0210f527a

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 7776f665-f356-4199-bc04-82734691b274
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column Metrica
		dataType: string
		lineageTag: bd4d28e6-6608-4a17-982f-be54da67b659
		summarizeBy: none
		sourceColumn: Metrica

		annotation SummarizationSetBy = Automatic

	partition _Misuresupporto = m
		mode: import
		source =
				let
				    Origine = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlTSUfINClIIyS9JzElVitWJVjICCkG4CqElqXklmWBRY6AohKvgWFKSWQYRNQGK+helKqRkKoRlFmfm50GMMAUKO2eUFuUpBCWWAIViAQ==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [ID = _t, Metrica = _t]),
				    #"Modificato tipo" = Table.TransformColumnTypes(Origine,{{"ID", Int64.Type}, {"Metrica", type text}})
				in
				    #"Modificato tipo"

	changedProperty = Name

	annotation PBI_ResultType = Table

